# Launch instances, runs some tasks
# and then terminate them
# This is already there in the ansible documentations, I a just consuming it.
- name: Playbook to create the ec2, do a dryn run and then self-destroy
  hosts: localhost
  gather_facts: False
  vars:
    instance_type: "t3.micro"
    #security_group_id: "sg-0ad44c710cefaf748"  # Update as per your security group id
    #image: "ami-024b3a099b37eaf47"             # Update this with the AMI ID in your account which has ansible installed.
    security_group_id: "sg-0200735cd456f6308"
    image: "ami-006234a9bfd5b5848"
    region: "us-east-1"
    #vpc_subnet_id : "vpc-37119c5f"
  tasks:
    - name: Launch instance
      amazon.aws.ec2:
        group_id: "{{ security_group_id }}"
        #vpc_subnet_id: "{{vpc_subnet_id}}"       
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        wait: true
        region: "{{ region }}"
        instance_tags:
          Name: ansible-dryrun-check
      register: ec2

    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: launched  # name of the group
      loop: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
      delegate_to: "{{ item.public_ip }}"
      wait_for_connection:
        delay: 50
        timeout: 90
      loop: "{{ ec2.instances }}"
      ignore_errors: yes

    - name: Set a Instance_ID Variable
      set_fact:
        INSTANCE_ID: "{{ ec2.instance_ids }}"

- name: Dry-Run the Role and Terminate the instance
  hosts: launched
  gather_facts: Yes
  tasks:
    - name: set the facts per host
      set_fact:
        INSTANCE_ID: "{{hostvars['localhost']['INSTANCE_ID']}}"

    - name: Import the role
      block:
        - name: Import a role
          import_role:
            name: "{{COMPONENT}}"
          ignore_errors: yes
          become: yes
      always:
        - name: Terminate instances that were previously launched
          delegate_to: 127.0.0.1
          amazon.aws.ec2:
            state: 'absent'
            instance_ids: '{{ INSTANCE_ID }}'
            region: us-east-1